# Generated by Django 4.1.4 on 2022-12-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('patronymic', models.CharField(max_length=45)),
                ('birthDate', models.DateField()),
                ('university', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='universities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=255)),
                ('shortName', models.CharField(max_length=45)),
                ('creationDate', models.DateField()),
            ],
        ),
    ]
