# Generated by Django 4.1.4 on 2022-12-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentsdatabase.universities'),
        ),
    ]
