# Generated by Django 4.1.4 on 2022-12-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdatabase', '0003_alter_students_id_alter_universities_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='universities',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
